// Material Design 3-inspired theme. All tokens stay compatible with the keys
// referenced across the app; extra MD3 roles (surfaceVariant, outline,
// secondary) are provided alongside.
export const palette = {
  // Brand blue family (Material-ish)
  primary: '#1A73E8',
  primaryDark: '#0B57D0',
  primaryLight: '#D2E3FC',
  primarySoft: '#E8F1FE',
  onPrimary: '#FFFFFF',

  // Secondary (teal) and tertiary accents
  secondary: '#00696D',
  secondarySoft: '#E4F6F7',
  tertiary: '#8B3FD6',
  tertiarySoft: '#F2E8FC',

  // Surfaces
  background: '#EEF2FA',
  surface: '#FFFFFF',
  surfaceVariant: '#E4EAF6',
  surfaceTint: '#EEF4FF',
  onSurface: '#1B1F3B',
  onSurfaceVariant: '#5A6478',
  outline: '#C0CBE0',
  border: '#DCE3F0',

  text: '#171C36',
  textSubtle: '#5A6478',

  // Feedback
  success: '#0E9F6E',
  successBg: '#E4F8F0',
  warning: '#E88F0D',
  warningBg: '#FFF4E2',
  danger: '#E5484D',
  dangerBg: '#FDECED',
  info: '#2196F3',
  infoBg: '#E6F3FF',

  navy: '#0C1B33',
  navyLight: '#16294A',
  white: '#FFFFFF',
} as const;

export const theme = {
  colors: {
    primary: palette.primary,
    primaryDark: palette.primaryDark,
    primarySoft: palette.primarySoft,
    primaryLight: palette.primaryLight,
    onPrimary: palette.onPrimary,
    secondary: palette.secondary,
    secondarySoft: palette.secondarySoft,
    tertiary: palette.tertiary,
    tertiarySoft: palette.tertiarySoft,
    background: palette.background,
    surface: palette.surface,
    surfaceVariant: palette.surfaceVariant,
    surfaceTint: palette.surfaceTint,
    onSurface: palette.onSurface,
    onSurfaceVariant: palette.onSurfaceVariant,
    outline: palette.outline,
    border: palette.border,
    text: palette.text,
    textSubtle: palette.textSubtle,
    success: palette.success,
    successBg: palette.successBg,
    warning: palette.warning,
    warningBg: palette.warningBg,
    danger: palette.danger,
    dangerBg: palette.dangerBg,
    info: palette.info,
    infoBg: palette.infoBg,
    navy: palette.navy,
    navyLight: palette.navyLight,
    white: palette.white,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    xs: 6,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 22,
    pill: 999,
  },
  text: {
    screenTitle: 28,
    title: 26,
    heading: 21,
    cardTitle: 17,
    body: 16,
    caption: 14,
    small: 12,
    mini: 11,
  },
  icon: {
    sm: 16,
    md: 20,
    lg: 26,
    xl: 34,
  },
  shadow: {
    card: {
      shadowColor: '#0B1C44',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
  },
} as const;